clovis/codigo/urls.py
"""
Rotas de URL do sistema
"""
from django.urls import path
from .views import *

app_name = 'codigo'

urlpatterns = [
    path('', AdminLogin.as_view(), name='admin-login'),
    path('home/', AdminHome.as_view(), name='admin-home'),
    path('configuracao/', AdminSetup.as_view(), name='admin-config'),
    path('registro/', AdminUserRegister.as_view(), name='admin-user-register'),
    path('log/', AdminLog.as_view(), name='admin-log'),

    path('entrada/', UserArrive.as_view(), name='user-arrive'),
    path('entrada/login', UserArriveLogin.as_view(), name='user-login'),
    path('entrada/ficha', UserArriveToken.as_view(), name='user-token'),

    path('saida/', UserDepart.as_view(), name='user-depart'),
    path('saida/pagamento', UserDepartPrice.as_view(), name='user-price'),
]

clovis/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('', include('codigo.urls', namespace='codigo')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

codigo/urls.py
"""
Rotas de URL do sistema
"""
from django.urls import path
from codigo.views import *

app_name = 'codigo'

urlpatterns = [
    path('', AdminLogin.as_view(), name='admin-login'),
    path('home/', AdminHome.as_view(), name='admin-home'),
    path('configuracao/', AdminSetup.as_view(), name='admin-config'),
    path('registro/', AdminUserRegister.as_view(), name='admin-user-register'),
    path('log/', AdminLog.as_view(), name='admin-log'),

    path('entrada/', UserArrive.as_view(), name='user-arrive'),
    path('entrada/login', UserArriveLogin.as_view(), name='user-login'),
    path('entrada/ficha', UserArriveToken.as_view(), name='user-token'),

    path('saida/', UserDepart.as_view(), name='user-depart'),
    path('saida/pagamento', UserDepartPrice.as_view(), name='user-price'),
]

codigo/models.py
"""
Arquivo de modelos do banco de dados seguindo o padrão do django
"""

from django.db import models


class Config(models.Model):
    """
    Modelo para configurações globais do sistema

    Obs.: Segue o padrão Singleton
    """
    preco = models.FloatField(verbose_name="Preço por Hora")
    vagas = models.PositiveIntegerField(verbose_name="Número de Vagas")

    def get_singleton():
        return Config.objects.first()


class Admin(models.Model):
    """
    Modelo para administrador do sistema
    """

    email = models.EmailField()
    senha = models.CharField()


class UsuarioCadastrado(models.Model):
    """
    Modelo para usuário cadastrado no sistema
    """

    cpf = models.CharField(max_length=11, null=False,
                           blank=False, primary_key=True, verbose_name="CPF")
    nome = models.CharField(max_length=50, null=False, blank=False)


class Ficha(models.Model):
    """
    Modelo para uma ficha registrada no sistema
    """

    horario_entrada = models.DateField(
        auto_now_add=True, verbose_name="Horário de Entrada")
    horario_saida = models.DateField(verbose_name="Horário de Saída")
    usuario = models.OneToOneField(
        UsuarioCadastrado, blank=True, null=True, on_delete=models.PROTECT)
    pago = models.BooleanField()

codigo/models/admin.py
from django.db import models


class Admin(models.Model):
    """
    Modelo para administrador do sistema
    """

    email = models.EmailField()
    senha = models.CharField(max_length=32)

    def __str__(self):
        return f'Admin {self.email}'

codigo/models/config.py
from django.db import models

class Config(models.Model):
    """
    Modelo para configurações globais do sistema
    
    Obs.: Utilize get_instance() para pegar as configurações globais
    do app (padrão Singleton)
    """

    preco = models.FloatField(null=False, blank=False)
    desconto = models.PositiveIntegerField(null=False, blank=False, default=30)
    vagas = models.PositiveIntegerField(null=False, blank=False)

    def get_instance():
        if not Config.objects.first():
            Config(preco=10.00, vagas=50, desconto=30).save()
        return Config.objects.first()
    
    def __str__(self):
        return f'Configurações do Sistema'

codigo/models/ficha.py
import math
from django.db import models
from .usuario_cadastrado import UsuarioCadastrado


class Ficha(models.Model):
    """
    Modelo para uma ficha registrada no sistema
    """

    horario_entrada = models.DateTimeField(
        auto_now_add=True, verbose_name="Horário de Entrada")
    horario_saida = models.DateTimeField(
        verbose_name="Horário de Saída", null=True)
    usuario = models.ForeignKey(
        UsuarioCadastrado, blank=True, null=True, on_delete=models.PROTECT)
    pago = models.BooleanField(default=False)
    valor = models.FloatField(null=True, blank=True)

    @property
    def diff_horas(self):
        """
        Retorna quantas horas o usuário passou estacionado, arredondando para cima,
        ou None quando não existe horário de saída
        """
        if self.horario_saida:
            return math.ceil(((self.horario_saida - self.horario_entrada).seconds) / 3600)
        return None

    def __str__(self):
        return f'Ficha {self.id}'

codigo/models/usuario_cadastrado.py
from django.db import models


class UsuarioCadastrado(models.Model):
    """
    Modelo para usuário cadastrado no sistema
    """

    cpf = models.CharField(max_length=11, null=False,
                           blank=False, primary_key=True, verbose_name="CPF")
    nome = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return f'{self.nome} ({self.cpf})'

codigo/templates/login/home.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% sass_src 'scss/login/home.scss' %}">
{% endblock head %}

{% block content %}
<div class="container-home">
    {% include 'utils/admin-header.html' %}

    <div class="main">
        <div class="main-home-container">
            <div class="control-button">
                <button>
                    <a href="{% url 'codigo:admin-user-register' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" fill="var(--white)"
                            viewBox="0 0 256 256">
                            <rect width="256" height="256" fill="none"></rect>
                            <circle cx="128" cy="120" r="40" fill="none" stroke="var(--white)" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="8"></circle>
                            <path d="M63.8,199.4a72,72,0,0,1,128.4,0" fill="none" stroke="var(--white)"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="8"></path>
                            <line x1="176" y1="56" x2="224" y2="56" fill="none" stroke="var(--white)"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="8"></line>
                            <line x1="200" y1="32" x2="200" y2="80" fill="none" stroke="var(--white)"
                                stroke-linecap="round" stroke-linejoin="round" stroke-width="8"></line>
                            <path d="M222.8,112.9A93.3,93.3,0,0,1,224,128a96,96,0,1,1-96-96,93.3,93.3,0,0,1,15.1,1.2"
                                fill="none" stroke="var(--white)" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="8"></path>
                        </svg>
                    </a>
                </button>
                <p>Cadastrar Usuário</p>
            </div>

            <div class="control-button">
                <button>
                    <a href="{% url 'codigo:admin-log' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" fill="#f1e9e9" 
                        viewBox="0 0 256 256"><rect width="256" height="256" fill="none"></rect>
                        <ellipse cx="128" cy="80" rx="88" ry="48" fill="none" stroke="#f1e9e9" 
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="8"></ellipse>
                        <path d="M40,80v48c0,26.5,39.4,48,88,48s88-21.5,88-48V80" fill="none" stroke="#f1e9e9" 
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="8"></path>
                        <path d="M40,128v48c0,26.5,39.4,48,88,48s88-21.5,88-48V128" fill="none" stroke="#f1e9e9" 
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="8"></path>
                        </svg>
                    </a>
                </button>
                <p>Registros</p>
            </div>

            <div class="control-button">
                <button>
                    <a href="{% url 'codigo:admin-config' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="192" height="192" fill="var(--white)"
                            viewBox="0 0 256 256">
                            <rect width="256" height="256" fill="none"></rect>
                            <circle cx="128" cy="128" r="48" fill="none" stroke="var(--white)" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="8"></circle>
                            <path
                                d="M183.7,65.1q3.8,3.5,7.2,7.2l27.3,3.9a103.2,103.2,0,0,1,10.2,24.6l-16.6,22.1s.3,6.8,0,10.2l16.6,22.1a102.2,102.2,0,0,1-10.2,24.6l-27.3,3.9s-4.7,4.9-7.2,7.2l-3.9,27.3a103.2,103.2,0,0,1-24.6,10.2l-22.1-16.6a57.9,57.9,0,0,1-10.2,0l-22.1,16.6a102.2,102.2,0,0,1-24.6-10.2l-3.9-27.3q-3.7-3.5-7.2-7.2l-27.3-3.9a103.2,103.2,0,0,1-10.2-24.6l16.6-22.1s-.3-6.8,0-10.2L27.6,100.8A102.2,102.2,0,0,1,37.8,76.2l27.3-3.9q3.5-3.7,7.2-7.2l3.9-27.3a103.2,103.2,0,0,1,24.6-10.2l22.1,16.6a57.9,57.9,0,0,1,10.2,0l22.1-16.6a102.2,102.2,0,0,1,24.6,10.2Z"
                                fill="none" stroke="var(--white)" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="8"></path>
                        </svg>
                    </a>
                </button>
                <p>Configurações</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/login/login.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% sass_src 'scss/login/login.scss' %}">
{% endblock head %}

{% block content %}
<div class="container">
    {% include 'utils/sidebar.html' with mensagem="faça seu login" %}
    <div class="main">
        <form action="" method="post">
            <h2>Login</h2>

            {% csrf_token %}
            <input name="email" type="email" placeholder="e-mail">
            <input name="password" type="password" placeholder="senha">

            <button>
                login
            </button>
            <div class="screens">
                <a href="{% url 'codigo:user-arrive' %}">tela de entrada</a>
                <a href="{% url 'codigo:user-depart' %}">tela de saída</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

codigo/templates/login/setup.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% sass_src 'scss/login/config.scss' %}">

{% endblock head %}

{% block content %}
<div class="container-home">
    {% include 'utils/admin-header.html' with back="codigo:admin-home" %}
    <div class="main">
        <div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="container-form hour-value-container">
                    <h2>Alterar valor da hora</h2>
                    <p>Valor atual: R$ {{ preco }}</p>
                    <div class="set-new-value">
                        <p>Novo valor: R$</p>
                        <input name="novoValorHora" type="number">
                    </div>
                </div>
                <div class="container-form parking-lot-container">
                    <h2>Estacionamento</h2>
                    <p>Veículos estacionados: {{ estacionados }}</p>
                    <p>Número de vagas disponíveis: {{ vagas }}</p>
                    <div class="set-new-value">
                        <p>Novo número de vagas: </p>
                        <input name="novoNumeroVagas" type="number">
                    </div>
                </div>
                <div class="container-form discount-value-container">
                    <h2>Desconto</h2>
                    <p>Desconto atual: {{ desconto }}%</p>
                    <div class="set-new-value">
                        <p>Novo valor: %</p>
                        <input name="novoValorDesconto" type="number">
                    </div>
                </div>
                <button class="bnt-primary">Alterar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/login/token-log.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<meta http-equiv="refresh" content="5; URL='{% url 'codigo:admin-log' %}'" />
<link rel="stylesheet" href="{% sass_src 'scss/login/token-log.scss' %}">
{% endblock head %}

{% block content %}
<div class="container-home">
    {% include 'utils/admin-header.html' with back='codigo:admin-home' %}
    <div class="main">
        <table>
            <thead>
                <tr>
                    <td>FICHA</td>
                    <td>PAGO/ESTACIONADO</td>
                    <td>HORÁRIO ENTRADA</td>
                    <td>HORÁRIO SAÍDA</td>
                    <td>NOME</td>
                    <td>PREÇO</td>
                </tr>
            </thead>
            <tbody>
                {% for item in estacionados %}
                <tr>
                    <td>{{item.id}}</td>
                    <td>{% if item.pago %}PAGO{% else %}ESTACIONADO{%  endif %}</td>
                    <td>{{item.horario_entrada|date:'d/m/y H:m'}}</td>
                    <td>{% if item.horario_saida %}{{item.horario_saida|date:'d/m/y H:m'}}{% else %}-{% endif %}</td>
                    <td>{% if item.usuario.nome %}{{item.usuario.nome}}{% else %}-{% endif %}</td>
                    <td>{% if item.valor %}{{item.valor}}{% else %}-{% endif %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

codigo/templates/login/user-register.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% sass_src 'scss/login/user-register.scss' %}">
{% endblock head %}

{% block content %}
<div class="container-home">
    {% include 'utils/admin-header.html' with back="codigo:admin-home" %}
    <div class="main">
        <div>
            <form action="" method="POST">
                <div class="container-form">
                    <h2>Cadastrar usuário:</h2>
                    {% csrf_token %}
                    <input id="username" name="userName" type="text" placeholder="nome do usuário">
                    <input id="cpfInput" name="cpf" type="text" placeholder="cpf">
                </div>
                    
                <button class="btn-primary">Cadastrar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/userArrive/entrada.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% sass_src 'scss/userArrive/entrada.scss' %}">
{% endblock head %}

{% block content %}
<div class="container">
    {% include 'utils/sidebar.html' with mensagem="seja bem vindo" %}
    <div class="main">
        <div>
            <h2>Confirme a sua entrada</h2>

            <div class="options-buttons">
                <a href="{% url 'codigo:user-login' %}">
                    <button class="btn-arrive registered">sou cadastrado</button>
                </a>
                <a href="{% url 'codigo:user-token' %}">
                    <form action="" method="post">
                        {% csrf_token %}
                        <button class="btn-arrive anonymous">entrada comum</button>
                    </form>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/userArrive/login.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% sass_src 'scss/userArrive/login.scss' %}">
{% endblock head %}

{% block content %}
<div class="container">
    {% include 'utils/sidebar.html' with mensagem="informe seus dados" %}
    <div class="main">
        <div>
            <form action="" method="post">
                <h2>Informe seu CPF</h2>
                {% csrf_token %}
                <input type="text" name="cpf" placeholder="cpf">

                <button class="btn-primary" type="submit">confirmar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/userArrive/token.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<meta http-equiv="refresh" content="15; URL='{% url 'codigo:user-arrive' %}'" />
<link rel="stylesheet" href="{% sass_src 'scss/userArrive/token.scss' %}">
{% endblock head %}

{% block content %}
<div class="container">
    {% include 'utils/sidebar.html' with mensagem="siga em diante" %}
    <div class="main">
        <h2>Essa é sua ficha{% if nome %}, {{nome}}.{% endif %}</h2>
        <div>{{ id }}</div>
    </div>
</div>
{% endblock content %}

codigo/templates/userDepart/price.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<meta http-equiv="refresh" content="15; URL='{% url 'codigo:user-depart' %}'" />
<link rel="stylesheet" href="{% sass_src 'scss/userDepart/price.scss' %}">
{% endblock head %}

{% block content %}
<div class="container">
    {% include 'utils/sidebar.html' with mensagem="até a próxima!" %}
    <div class="main">
        <div id="price">
            <h2>Valor:</h2>
            <div class="valor">R$ {{ preco }}</div>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/userDepart/saida.html
{% extends 'utils/base.html' %}
{% load sass_tags %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% sass_src 'scss/userDepart/saida.scss' %}">
{% endblock head %}

{% block content %}
<div class="container">
    {% include 'utils/sidebar.html' with mensagem="hora de sair..." %}
    <div class="main">
        <div>
            <form action="" method="POST">
                <h2>Informe sua ficha</h2>
                {% csrf_token %}
                <input name="ficha" type="text" placeholder="ficha">

                <button class="btn-primary">confirmar</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

codigo/templates/utils/admin-header.html
<header>
    <div>
        <h1>ZÉ CLOVIS</h1>
        <div class="header-buttons">
            {% if back %}
            <a href="{% url back %}"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="var(--white)"
                    viewBox="0 0 256 256">
                    <rect width="256" height="256" fill="none"></rect>
                    <circle cx="128" cy="128" r="96" fill="none" stroke="var(--white)" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="12"></circle>
                    <polyline points="121.9 161.9 88 128 121.9 94.1" fill="none" stroke="var(--white)"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="12"></polyline>
                    <line x1="88" y1="128" x2="168" y2="128" fill="none" stroke="var(--white)" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="12"></line>
                </svg></a>{% endif %}
            <a href="{% url 'codigo:admin-login' %}"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48"
                    fill="var(--red)" viewBox="0 0 256 256">
                    <rect width="256" height="256" fill="none"></rect>
                    <line x1="128" y1="48" x2="128" y2="124" fill="none" stroke="var(--red)" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="8"></line>
                    <path d="M176,54.2a88,88,0,1,1-96,0" fill="none" stroke="var(--red)" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="12"></path>
                </svg></a>
        </div>
    </div>
</header>

codigo/templates/utils/base.html
{% load sass_tags %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CLOVIS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{% sass_src 'scss/global/global.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'scss/global/alert.scss' %}">
    <link
    href="https://fonts.googleapis.com/css2?family=Jost:wght@200;300;400;500;600;700;800;900&family=Montserrat:wght@300;400;500;600;700&display=swap"
    rel="stylesheet">
    {% block head %}{% endblock head %}
</head>
<body>
    <div class="alerts">
        {% for message in messages %}
        <div class="alert">
            <p><b>Erro: </b>{{ message }}</p>
        </div>
        {% endfor %}
    </div>
    {% block content %}{% endblock content %}
    {% block scripts %}{% endblock scripts %}
</body>
</html>

codigo/templates/utils/sidebar.html
<div class="sidebar">
    <h1>ZÉ CLOVIS</h1>
    <p>{{ mensagem }}</p>
</div>